name: flutterpgp
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: '>=2.0.0 <3.0.0'
flutter:
  plugin:
    androidPackage: com.example.flutterpgp
    pluginClass: FlutterpgpPlugin
